name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 15

      - uses: actions/cache@v2
        if: ${{ !env.ACT }} # skip step when running locally with nektos/act
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - name: TSC type checking
        run: npx tsc --noEmit

      - name: ESLint
        run: npx eslint .

      - name: Run vite build
        run: npm run build
